const path = require("path");
const fs = require('fs');

const root = path.resolve(__dirname, "..");
const lock = JSON.parse(fs.readFileSync(path.join(root, "package-lock.json")));
const dest = path.join(root, "src", "versions.ts")

var code = [
    "// Do not edit this file; run scripts/versions.js instead",
    "export function versions() {",
    "    return {",
    `        random: "${lock.packages["node_modules/@reside-ic/random"].version}",`,
    `        odinjs: "${lock.packages["node_modules/@reside-ic/odinjs"].version}",`,
    `        dust: "${lock.version}",`,
    "    };",
    "}"];

fs.writeFileSync(dest, code.map((x) => x + "\n").join(""));
